In [1]:
import sys
if 'google.colab' in sys.modules:
  !pip install pyrosettacolabsetup
  import pyrosettacolabsetup
  pyrosettacolabsetup.mount_pyrosetta_install()
from pyrosetta import *
init()

Collecting pyrosettacolabsetup
  Downloading pyrosettacolabsetup-1.1.0-py3-none-any.whl.metadata (406 bytes)
Downloading pyrosettacolabsetup-1.1.0-py3-none-any.whl (5.0 kB)
Installing collected packages: pyrosettacolabsetup
Successfully installed pyrosettacolabsetup-1.1.0
Mounted at /content/google_drive

Note that USE OF PyRosetta FOR COMMERCIAL PURPOSES REQUIRE PURCHASE OF A LICENSE.
See https://github.com/RosettaCommons/rosetta/blob/main/LICENSE.md or email license@uw.edu for details.

Looking for compatible PyRosetta wheel file at google-drive/PyRosetta/colab.bin//wheels...
Downloading PyRosetta package...
--2026-07-23 00:04:41--  https://west.rosettacommons.org/pyrosetta/quarterly/release/pyrosetta-0-cp312-cp312-linux_x86_64.whl

Connecting to west.rosettacommons.org (west.rosettacommons.org)|128.95.160.135|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 1662376546 (1.5G) [application/octet-stream]
--2026-07-23 00:04:41--  https://west.rosettacommons.org/pyrosetta/quarterly/release/pyrosetta-0-cp312-cp312-linux_x86_64.whl

HTTP request sent, awaiting response... 200 OK
Length: 1662376546 (1.5G) [application/octet-stream]
Saving to: ‘/content/google_drive/MyDrive/PyRosetta/colab.bin/tmpj3540xmh/pyrosetta-0-cp312-cp312-linux_x86_64.whl’

pyrosetta-0-cp312-c 100%[===================>]   1.55G  31.1MB/s    in 75s

2026-07-23 00:05:56 (21.3 MB/s) - ‘/content/google_drive/MyDrive/PyRosetta/colab.bin/tmpj3540xmh/pyrosetta-0-cp312-cp312-linux_x86_64.whl’ saved [1662376546/1662376546]
Moving wheel file pyrosetta-0-cp312-cp312-linux_x86_64.whl to target dir /content/google_drive/MyDrive/PyRosetta/colab.bin/wheels...
Installing PyRosetta wheel '/content/google_drive/MyDrive/PyRosetta/colab.bin/wheels/pyrosetta-0-cp312-cp312-linux_x86_64.whl'...



┌───────────────────────────────────────────────────────────────────────────────┐
│                                  PyRosetta-4                                  │
│               Created in JHU by Sergey Lyskov and PyRosetta Team              │
│               (C) Copyright Rosetta Commons Member Institutions               │
│                                                                               │
│ NOTE: USE OF PyRosetta FOR COMMERCIAL PURPOSES REQUIRES PURCHASE OF A LICENSE │
│          See LICENSE.PyRosetta.md or email license@uw.edu for details         │
└───────────────────────────────────────────────────────────────────────────────┘
PyRosetta-4 2026 [Rosetta PyRosetta4.Release.python312.ubuntu 2026.03+releasequarterly.5e498f1409c68ade56c8ce5842bf79e1b02e8db4 2026-01-13T13:24:11] retrieved from: http://www.pyrosetta.org
core.init: Checking for fconfig files in pwd and ./rosetta/flags
core.init: Rosetta version: PyRosetta4.Release.python312.ubuntu r1 2026.03+releasequarterly.5e498f1409 5e498f1409c68ade56c8ce5842bf79e1b02e8db4 http://www.pyrosetta.org 2026-01-13T13:24:11
core.init: Rosetta extras: []
core.init: command: PyRosetta -ex1 -ex2aro -database /usr/local/lib/python3.12/dist-packages/pyrosetta/database
basic.random.init_random_generator: 'RNG device' seed mode, using '/dev/urandom', seed=2057700168 seed_offset=0 real_seed=2057700168
basic.random.init_random_generator: RandomGenerator:init: Normal mode, seed=2057700168 RG_type=mt19937

##Get a PDB
Go to the REU 2026 Bootcamp Website and download the PDB
This PDB is a file of a de-novo designed binder bound to the Sirtuin-1 protein.


P53 is a tumor suppressor protein and SIRT-1 has been thought to downregulate P53 in response to DNA damage or cell stress, inhibiting P53's tumor suppressor functionality. It's tumor suppressor functionality extends to cell apoptosis (getting rid of damaged DNA), sensence, and plays a role in the cell cycle to help get rid of mutated DNA. Blocking this interaction between the SIRT1 protein and P53 with a binder could help inhibit P53's downregulation.


We're going to analyze the interface of this interaction between SIRT-1 and the de-novo binder


Upload the pdb file into the next upload cell

In [2]:
from google.colab import files

uploaded = files.upload()

pdb_file = next(iter(uploaded))
print(f"Uploaded: {pdb_file}")

Saving r4_i6_0_85_seq_1049_seq_911_unrelaxed_rank_001_alphafold2_multimer_v3_model_1_seed_000_relaxed.pdb to r4_i6_0_85_seq_1049_seq_911_unrelaxed_rank_001_alphafold2_multimer_v3_model_1_seed_000_relaxed.pdb
Uploaded: r4_i6_0_85_seq_1049_seq_911_unrelaxed_rank_001_alphafold2_multimer_v3_model_1_seed_000_relaxed.pdb

##Load your PDB File

In [3]:
from pyrosetta import *

pose = pose_from_pdb(pdb_file)

print("Loaded:", pdb_file)
print("Residues:", pose.total_residue())

core.chemical.GlobalResidueTypeSet: Finished initializing fa_standard residue type set.  Created 985 residue types
core.chemical.GlobalResidueTypeSet: Total time to initialize 1.59376 seconds.
core.import_pose.import_pose: File 'r4_i6_0_85_seq_1049_seq_911_unrelaxed_rank_001_alphafold2_multimer_v3_model_1_seed_000_relaxed.pdb' automatically determined to be of type PDB from contents.
Loaded: r4_i6_0_85_seq_1049_seq_911_unrelaxed_rank_001_alphafold2_multimer_v3_model_1_seed_000_relaxed.pdb
Residues: 416

In [4]:
# @title
import ipywidgets as widgets
from IPython.display import display, Markdown

display(Markdown("## Checkpoint: Interface Analyzer Questions"))

questions = {
    "Interface Analyzer Questions": [
        "Knowing that this binder was designed to bind to SIRT1, how do you think the interface analyzer will score the delta of the interface?",
        "How do you think the interface analyzer will score the delta G of the separated chains?",
        "How do you think the SASA will be affected when bound vs unboud to each other?",
    ],
}
answer_boxes = {}

for section, qs in questions.items():

    display(Markdown(f"### {section}"))

    for q in qs:

        display(Markdown(f"**{q}**"))

        box = widgets.Textarea(
            placeholder="Enter your answer here...",
            layout=widgets.Layout(width='90%', height='20%')
        )

        answer_boxes[q] = box
        display(box)

## Checkpoint: Interface Analyzer Questions

### Interface Analyzer Questions

**Knowing that this binder was designed to bind to SIRT1, how do you think the interface analyzer will score the delta of the interface?**

Textarea(value='', layout=Layout(height='20%', width='90%'), placeholder='Enter your answer here...')

**How do you think the interface analyzer will score the delta G of the separated chains?**

Textarea(value='', layout=Layout(height='20%', width='90%'), placeholder='Enter your answer here...')

**How do you think the SASA will be affected when bound vs unboud to each other?**

Textarea(value='', layout=Layout(height='20%', width='90%'), placeholder='Enter your answer here...')

In [5]:
interface = "A_B"

##Run Rosetta Interface Analyzer

In [6]:
# @title
import pandas as pd
from pyrosetta.rosetta.protocols.analysis import InterfaceAnalyzerMover
from pyrosetta.rosetta.protocols.simple_filters import ShapeComplementarityFilter
from pyrosetta.rosetta.protocols.simple_filters import BuriedUnsatHbondFilter

sc = ShapeComplementarityFilter()

print("SC:", sc.compute(pose))


buns = BuriedUnsatHbondFilter()

print(buns.compute(pose))
iam = InterfaceAnalyzerMover(interface)
iam.set_compute_packstat(True)

print("Running InterfaceAnalyzer...")
iam.apply(pose)

for m in dir(iam):
    if "hbond" in m.lower():
        print(m)

results = {}

for method_name in dir(iam):

    if not method_name.startswith("get_"):
        continue

    try:
        method = getattr(iam, method_name)

        if callable(method):
            value = method()

            if isinstance(value, (int, float, str, bool)):
                results[method_name] = value

    except:
        pass

df = pd.DataFrame(
    list(results.items()),
    columns=["Metric", "Value"]
)
df = df[
    ~df["Metric"].isin([
        "get_pymol_sel_hbond_unsat",
        "get_pymol_sel_interface",
        "get_pymol_sel_packing",
    ])
]

display(df)

# ---------------------------------
# Save CSV named after PDB
# ---------------------------------

csv_name = pdb_file.replace(".pdb", "_rosetta_metrics.csv")

df.to_csv(csv_name, index=False)

print(f"\nSaved: {csv_name}")

basic.io.database: Database file opened: scoring/score_functions/sc/sc_radii.lib
SC: <pyrosetta.rosetta.core.scoring.sc._RESULTS object at 0x7dc1c44e84f0>
protocols.simple_filters.BuriedUnsatHbondFilter: /////////////////////////////////////////////////////////////////////////////////////////
protocols.simple_filters.BuriedUnsatHbondFilter:
protocols.simple_filters.BuriedUnsatHbondFilter:     USING DEFAULT BEHAVIOR: filter will report total number of heavy-atom donor/acceptor buried unsats
protocols.simple_filters.BuriedUnsatHbondFilter:
protocols.simple_filters.BuriedUnsatHbondFilter: /////////////////////////////////////////////////////////////////////////////////////////
protocols.simple_filters.BuriedUnsatHbondFilter:
core.scoring.ScoreFunctionFactory: SCOREFUNCTION: ref2015
core.scoring.etable: Starting energy table calculation
core.scoring.etable: smooth_etable: changing atr/rep split to bottom of energy well
core.scoring.etable: smooth_etable: spline smoothing lj etables (maxdis = 6)
core.scoring.etable: smooth_etable: spline smoothing solvation etables (max_dis = 6)
core.scoring.etable: Finished calculating energy tables.
basic.io.database: Database file opened: scoring/score_functions/hbonds/ref2015_params/HBPoly1D.csv
basic.io.database: Database file opened: scoring/score_functions/hbonds/ref2015_params/HBFadeIntervals.csv
basic.io.database: Database file opened: scoring/score_functions/hbonds/ref2015_params/HBEval.csv
basic.io.database: Database file opened: scoring/score_functions/hbonds/ref2015_params/DonStrength.csv
basic.io.database: Database file opened: scoring/score_functions/hbonds/ref2015_params/AccStrength.csv
basic.io.database: Database file opened: scoring/score_functions/rama/fd/all.ramaProb
basic.io.database: Database file opened: scoring/score_functions/rama/fd/prepro.ramaProb
basic.io.database: Database file opened: scoring/score_functions/omega/omega_ppdep.all.txt
basic.io.database: Database file opened: scoring/score_functions/omega/omega_ppdep.gly.txt
basic.io.database: Database file opened: scoring/score_functions/omega/omega_ppdep.pro.txt
basic.io.database: Database file opened: scoring/score_functions/omega/omega_ppdep.valile.txt
basic.io.database: Database file opened: scoring/score_functions/P_AA_pp/P_AA
basic.io.database: Database file opened: scoring/score_functions/P_AA_pp/P_AA_n
core.scoring.P_AA: shapovalov_lib::shap_p_aa_pp_smooth_level of 1( aka low_smooth ) got activated.
basic.io.database: Database file opened: scoring/score_functions/P_AA_pp/shapovalov/10deg/kappa131/a20.prop
basic.io.database: Database file opened: scoring/score_functions/elec_cp_reps.dat
core.scoring.elec.util: Read 40 countpair representative atoms
core.pack.dunbrack.RotamerLibrary: shapovalov_lib_fixes_enable option is true.
core.pack.dunbrack.RotamerLibrary: shapovalov_lib::shap_dun10_smooth_level of 1( aka lowest_smooth ) got activated.
core.pack.dunbrack.RotamerLibrary: Binary rotamer library selected: /usr/local/lib/python3.12/dist-packages/pyrosetta/database/rotamer/shapovalov/StpDwn_0-0-0/Dunbrack10.lib.bin
core.pack.dunbrack.RotamerLibrary: Using Dunbrack library binary file '/usr/local/lib/python3.12/dist-packages/pyrosetta/database/rotamer/shapovalov/StpDwn_0-0-0/Dunbrack10.lib.bin'.
core.pack.dunbrack.RotamerLibrary: Dunbrack 2010 library took 0.231932 seconds to load from binary
basic.io.database: Database file opened: scoring/score_functions/hbonds/sp2_elec_params/HBPoly1D.csv
basic.io.database: Database file opened: scoring/score_functions/hbonds/sp2_elec_params/HBFadeIntervals.csv
basic.io.database: Database file opened: scoring/score_functions/hbonds/sp2_elec_params/HBEval.csv
protocols.vardist_solaccess: VarSolDistSasaCalculator::recompute
protocols.vardist_solaccess: VarSolDistSasaCalculator::lookup
protocols.vardist_solaccess: VarSolDistSasaCalculator::lookup
protocols.simple_filters.BuriedUnsatHbondFilter:   buried unsats in input pose:
protocols.simple_filters.BuriedUnsatHbondFilter:   all_heavy_atom_unsats = 55
protocols.simple_filters.BuriedUnsatHbondFilter:   bb_heavy_atom_unsats = 49
protocols.simple_filters.BuriedUnsatHbondFilter:   sc_heavy_atom_unsats = 6
protocols.simple_filters.BuriedUnsatHbondFilter:   countable_nonheavy_unsats = 37
protocols.simple_filters.BuriedUnsatHbondFilter:       Unsatisfied HEAVY polar atom at residue 3: GLU  N
protocols.simple_filters.BuriedUnsatHbondFilter:       Unsatisfied Hpol polar atom at residue 3: GLU  H
protocols.simple_filters.BuriedUnsatHbondFilter:       Unsatisfied HEAVY polar atom at residue 20: ALA  O
protocols.simple_filters.BuriedUnsatHbondFilter:       Unsatisfied HEAVY polar atom at residue 23: GLY  N
protocols.simple_filters.BuriedUnsatHbondFilter:       Unsatisfied Hpol polar atom at residue 23: GLY  H
protocols.simple_filters.BuriedUnsatHbondFilter:       Unsatisfied HEAVY polar atom at residue 26: SER  N
protocols.simple_filters.BuriedUnsatHbondFilter:       Unsatisfied Hpol polar atom at residue 26: SER  H
protocols.simple_filters.BuriedUnsatHbondFilter:       Unsatisfied HEAVY polar atom at residue 39: VAL  O
protocols.simple_filters.BuriedUnsatHbondFilter:       Unsatisfied HEAVY polar atom at residue 43: LEU  O
protocols.simple_filters.BuriedUnsatHbondFilter:       Unsatisfied HEAVY polar atom at residue 46: PHE  N
protocols.simple_filters.BuriedUnsatHbondFilter:       Unsatisfied Hpol polar atom at residue 46: PHE  H
protocols.simple_filters.BuriedUnsatHbondFilter:       Unsatisfied HEAVY polar atom at residue 49: GLU  N
protocols.simple_filters.BuriedUnsatHbondFilter:       Unsatisfied Hpol polar atom at residue 49: GLU  H
protocols.simple_filters.BuriedUnsatHbondFilter:       Unsatisfied HEAVY polar atom at residue 75: VAL  N
protocols.simple_filters.BuriedUnsatHbondFilter:       Unsatisfied Hpol polar atom at residue 75: VAL  H
protocols.simple_filters.BuriedUnsatHbondFilter:       Unsatisfied HEAVY polar atom at residue 98: TYR  N
protocols.simple_filters.BuriedUnsatHbondFilter:       Unsatisfied Hpol polar atom at residue 98: TYR  H
protocols.simple_filters.BuriedUnsatHbondFilter:       Unsatisfied HEAVY polar atom at residue 99: THR  N
protocols.simple_filters.BuriedUnsatHbondFilter:       Unsatisfied Hpol polar atom at residue 99: THR  H
protocols.simple_filters.BuriedUnsatHbondFilter:       Unsatisfied HEAVY polar atom at residue 100: PHE  N
protocols.simple_filters.BuriedUnsatHbondFilter:       Unsatisfied Hpol polar atom at residue 100: PHE  H
protocols.simple_filters.BuriedUnsatHbondFilter:       Unsatisfied HEAVY polar atom at residue 121: GLU  N
protocols.simple_filters.BuriedUnsatHbondFilter:       Unsatisfied Hpol polar atom at residue 121: GLU  H
protocols.simple_filters.BuriedUnsatHbondFilter:       Unsatisfied Hpol polar atom at residue 147: ARG 1HH1
protocols.simple_filters.BuriedUnsatHbondFilter:       Unsatisfied HEAVY polar atom at residue 153: ILE  N
protocols.simple_filters.BuriedUnsatHbondFilter:       Unsatisfied Hpol polar atom at residue 153: ILE  H
protocols.simple_filters.BuriedUnsatHbondFilter:       Unsatisfied HEAVY polar atom at residue 166: CYS  O
protocols.simple_filters.BuriedUnsatHbondFilter:       Unsatisfied HEAVY polar atom at residue 179: VAL  N
protocols.simple_filters.BuriedUnsatHbondFilter:       Unsatisfied Hpol polar atom at residue 179: VAL  H
protocols.simple_filters.BuriedUnsatHbondFilter:       Unsatisfied HEAVY polar atom at residue 183: ILE  N
protocols.simple_filters.BuriedUnsatHbondFilter:       Unsatisfied Hpol polar atom at residue 183: ILE  H
protocols.simple_filters.BuriedUnsatHbondFilter:       Unsatisfied HEAVY polar atom at residue 186: PHE  N
protocols.simple_filters.BuriedUnsatHbondFilter:       Unsatisfied Hpol polar atom at residue 186: PHE  H
protocols.simple_filters.BuriedUnsatHbondFilter:       Unsatisfied HEAVY polar atom at residue 195: ARG  NE
protocols.simple_filters.BuriedUnsatHbondFilter:       Unsatisfied Hpol polar atom at residue 195: ARG  HE
protocols.simple_filters.BuriedUnsatHbondFilter:       Unsatisfied HEAVY polar atom at residue 205: ASP  N
protocols.simple_filters.BuriedUnsatHbondFilter:       Unsatisfied Hpol polar atom at residue 205: ASP  H
protocols.simple_filters.BuriedUnsatHbondFilter:       Unsatisfied HEAVY polar atom at residue 213: GLU  N
protocols.simple_filters.BuriedUnsatHbondFilter:       Unsatisfied Hpol polar atom at residue 213: GLU  H
protocols.simple_filters.BuriedUnsatHbondFilter:       Unsatisfied HEAVY polar atom at residue 215: PHE  O
protocols.simple_filters.BuriedUnsatHbondFilter:       Unsatisfied HEAVY polar atom at residue 218: ASP  O
protocols.simple_filters.BuriedUnsatHbondFilter:       Unsatisfied HEAVY polar atom at residue 229: ILE  O
protocols.simple_filters.BuriedUnsatHbondFilter:       Unsatisfied HEAVY polar atom at residue 230: TYR  O
protocols.simple_filters.BuriedUnsatHbondFilter:       Unsatisfied HEAVY polar atom at residue 230: TYR  OH
protocols.simple_filters.BuriedUnsatHbondFilter:       Unsatisfied HEAVY polar atom at residue 239: CYS  N
protocols.simple_filters.BuriedUnsatHbondFilter:       Unsatisfied Hpol polar atom at residue 239: CYS  H
protocols.simple_filters.BuriedUnsatHbondFilter:       Unsatisfied HEAVY polar atom at residue 240: HIS  NE2
protocols.simple_filters.BuriedUnsatHbondFilter:       Unsatisfied Hpol polar atom at residue 240: HIS  HE2
protocols.simple_filters.BuriedUnsatHbondFilter:       Unsatisfied HEAVY polar atom at residue 255: ASN  OD1
protocols.simple_filters.BuriedUnsatHbondFilter:       Unsatisfied HEAVY polar atom at residue 260: ILE  O
protocols.simple_filters.BuriedUnsatHbondFilter:       Unsatisfied HEAVY polar atom at residue 265: GLN  N
protocols.simple_filters.BuriedUnsatHbondFilter:       Unsatisfied Hpol polar atom at residue 265: GLN  H
protocols.simple_filters.BuriedUnsatHbondFilter:       Unsatisfied HEAVY polar atom at residue 275: CYS  O
protocols.simple_filters.BuriedUnsatHbondFilter:       Unsatisfied HEAVY polar atom at residue 278: SER  O
protocols.simple_filters.BuriedUnsatHbondFilter:       Unsatisfied HEAVY polar atom at residue 279: PHE  N
protocols.simple_filters.BuriedUnsatHbondFilter:       Unsatisfied Hpol polar atom at residue 279: PHE  H
protocols.simple_filters.BuriedUnsatHbondFilter:       Unsatisfied HEAVY polar atom at residue 281: THR  N
protocols.simple_filters.BuriedUnsatHbondFilter:       Unsatisfied Hpol polar atom at residue 281: THR  H
protocols.simple_filters.BuriedUnsatHbondFilter:       Unsatisfied HEAVY polar atom at residue 286: ILE  N
protocols.simple_filters.BuriedUnsatHbondFilter:       Unsatisfied Hpol polar atom at residue 286: ILE  H
protocols.simple_filters.BuriedUnsatHbondFilter:       Unsatisfied HEAVY polar atom at residue 287: CYS  N
protocols.simple_filters.BuriedUnsatHbondFilter:       Unsatisfied Hpol polar atom at residue 287: CYS  H
protocols.simple_filters.BuriedUnsatHbondFilter:       Unsatisfied HEAVY polar atom at residue 288: LYS  N
protocols.simple_filters.BuriedUnsatHbondFilter:       Unsatisfied Hpol polar atom at residue 288: LYS  H
protocols.simple_filters.BuriedUnsatHbondFilter:       Unsatisfied HEAVY polar atom at residue 289: TYR  N
protocols.simple_filters.BuriedUnsatHbondFilter:       Unsatisfied Hpol polar atom at residue 289: TYR  H
protocols.simple_filters.BuriedUnsatHbondFilter:       Unsatisfied HEAVY polar atom at residue 304: VAL  O
protocols.simple_filters.BuriedUnsatHbondFilter:       Unsatisfied HEAVY polar atom at residue 310: ARG  N
protocols.simple_filters.BuriedUnsatHbondFilter:       Unsatisfied Hpol polar atom at residue 310: ARG  H
protocols.simple_filters.BuriedUnsatHbondFilter:       Unsatisfied HEAVY polar atom at residue 311: CYS  N
protocols.simple_filters.BuriedUnsatHbondFilter:       Unsatisfied Hpol polar atom at residue 311: CYS  H
protocols.simple_filters.BuriedUnsatHbondFilter:       Unsatisfied HEAVY polar atom at residue 314: ASP  N
protocols.simple_filters.BuriedUnsatHbondFilter:       Unsatisfied Hpol polar atom at residue 314: ASP  H
protocols.simple_filters.BuriedUnsatHbondFilter:       Unsatisfied HEAVY polar atom at residue 320: MET  O
protocols.simple_filters.BuriedUnsatHbondFilter:       Unsatisfied HEAVY polar atom at residue 335: PHE  N
protocols.simple_filters.BuriedUnsatHbondFilter:       Unsatisfied Hpol polar atom at residue 335: PHE  H
protocols.simple_filters.BuriedUnsatHbondFilter:       Unsatisfied HEAVY polar atom at residue 347: ASP  OD1
protocols.simple_filters.BuriedUnsatHbondFilter:       Unsatisfied HEAVY polar atom at residue 348: LEU  N
protocols.simple_filters.BuriedUnsatHbondFilter:       Unsatisfied Hpol polar atom at residue 348: LEU  H
protocols.simple_filters.BuriedUnsatHbondFilter:       Unsatisfied HEAVY polar atom at residue 355: SER  O
protocols.simple_filters.BuriedUnsatHbondFilter:       Unsatisfied HEAVY polar atom at residue 361: VAL  N
protocols.simple_filters.BuriedUnsatHbondFilter:       Unsatisfied Hpol polar atom at residue 361: VAL  H
protocols.simple_filters.BuriedUnsatHbondFilter:       Unsatisfied HEAVY polar atom at residue 368: ILE  N
protocols.simple_filters.BuriedUnsatHbondFilter:       Unsatisfied Hpol polar atom at residue 368: ILE  H
protocols.simple_filters.BuriedUnsatHbondFilter:       Unsatisfied HEAVY polar atom at residue 370: HIS  ND1
protocols.simple_filters.BuriedUnsatHbondFilter:       Unsatisfied HEAVY polar atom at residue 372: VAL  O
protocols.simple_filters.BuriedUnsatHbondFilter:       Unsatisfied HEAVY polar atom at residue 380: GLU  N
protocols.simple_filters.BuriedUnsatHbondFilter:       Unsatisfied Hpol polar atom at residue 380: GLU  H
protocols.simple_filters.BuriedUnsatHbondFilter:       Unsatisfied HEAVY polar atom at residue 396: ASP  N
protocols.simple_filters.BuriedUnsatHbondFilter:       Unsatisfied Hpol polar atom at residue 396: ASP  H
protocols.simple_filters.BuriedUnsatHbondFilter:       Unsatisfied HEAVY polar atom at residue 415: CYS  N
protocols.simple_filters.BuriedUnsatHbondFilter:       Unsatisfied Hpol polar atom at residue 415: CYS  H
protocols.simple_filters.BuriedUnsatHbondFilter:  WARNING! use_reporter_behavior=true, need to set one behavior to true; will use default report_all_heavy_atom_unsats:
55.0
Running InterfaceAnalyzer...
protocols.analysis.InterfaceAnalyzerMover: Using explicit constructor
protocols.analysis.InterfaceAnalyzerMover: Using interface constructor
protocols.evaluation.ChiWellRmsdEvaluatorCreator: Evaluation Creator active ...
protocols.analysis.InterfaceAnalyzerMover: Making an interface set with fixed chains
protocols.analysis.InterfaceAnalyzerMover: Interface set residues total: 69
protocols.analysis.InterfaceAnalyzerMover: NULL scorefunction. Initialize from cmd line.
core.scoring.ScoreFunctionFactory: SCOREFUNCTION: ref2015
protocols.analysis.InterfaceAnalyzerMover: Detecting disulfides in the separated pose.
protocols.analysis.InterfaceAnalyzerMover: Calculating dSASA
protocols.analysis.InterfaceAnalyzerMover: Calculating per-res dSASA data
protocols.analysis.InterfaceAnalyzerMover: included_nres: 416
protocols.analysis.InterfaceAnalyzerMover: Making hbond ScoreFunction with bb-bb energy method options
core.scoring.ScoreFunctionFactory: SCOREFUNCTION: ref2015
protocols.analysis.InterfaceAnalyzerMover: Found Hbond between chains: 2 and 1
protocols.analysis.InterfaceAnalyzerMover: Found Hbond between chains: 2 and 1
protocols.analysis.InterfaceAnalyzerMover: Found Hbond between chains: 2 and 1
protocols.analysis.InterfaceAnalyzerMover: Found Hbond between chains: 2 and 1
protocols.analysis.InterfaceAnalyzerMover: Found Hbond between chains: 1 and 2
protocols.analysis.InterfaceAnalyzerMover: Found Hbond between chains: 2 and 1
protocols.analysis.InterfaceAnalyzerMover: Computing interface packstats.
protocols.analysis.InterfaceAnalyzerMover: Total: 416 PackScoresTotal: 416
protocols.analysis.InterfaceAnalyzerMover: Computing delta unsat polar residues...
protocols.analysis.InterfaceAnalyzerMover: Computing Shape Complementarity Score...
protocols.analysis.InterfaceAnalyzerMover: Upstream chain(s) numbers: 1,
protocols.analysis.InterfaceAnalyzerMover: Downstream chain(s) numbers: 2,
get_interface_delta_hbond_unsat
get_pymol_sel_hbond_unsat
get_total_Hbond_E
set_calc_hbond_sasaE
set_compute_interface_delta_hbond_unsat

                                  Metric                   Value
0                        get_centroid_dG                     0.0
1                     get_complex_energy             -914.572731
2                     get_complexed_sasa            20981.078125
3         get_crossterm_interface_energy              -24.960541
4   get_crossterm_interface_energy_ratio               -0.013806
5                        get_current_tag                   NoTag
6               get_gly_interface_energy                     0.0
7                       get_interface_dG              -24.960541
8        get_interface_delta_hbond_unsat                       7
9               get_interface_delta_sasa             1807.967622
10                get_interface_packstat                0.539047
11            get_multichain_constructor                    True
12                              get_name  InterfaceAnalyzerMover
13            get_num_interface_residues                      69
14                        get_pack_input                   False
15                get_per_residue_energy               -1.910583
19        get_scorefile_reporting_prefix
20        get_separated_interface_energy              -24.960541
21  get_separated_interface_energy_ratio               -0.013806
22                        get_side1_nres                      31
23                       get_side1_score              -81.065426
24                        get_side2_nres                      38
25                       get_side2_score              -50.764775
26                     get_total_Hbond_E               -7.829421
27                              get_type       InterfaceAnalyzer
28                   get_use_centroid_dG                   False

Saved: r4_i6_0_85_seq_1049_seq_911_unrelaxed_rank_001_alphafold2_multimer_v3_model_1_seed_000_relaxed_rosetta_metrics.csv

In [7]:
# @title
import ipywidgets as widgets
from IPython.display import display, Markdown

display(Markdown("## Checkpoint: Interface Analyzer Questions"))

questions = {
    "Interface Analyzer Questions": [
        "How many interface residues does your protein complex have?",
        "What is the complexed energy? Is this a strong complexed energy?",
        "What is the number of residues on side 1 vs side 2?",
        "What is your per residue energy?",

    ],
}
answer_boxes = {}

for section, qs in questions.items():

    display(Markdown(f"### {section}"))

    for q in qs:

        display(Markdown(f"**{q}**"))

        box = widgets.Textarea(
            placeholder="Enter your answer here...",
            layout=widgets.Layout(width='90%', height='20%')
        )

        answer_boxes[q] = box
        display(box)

## Checkpoint: Interface Analyzer Questions

### Interface Analyzer Questions

**How many interface residues does your protein complex have?**

Textarea(value='', layout=Layout(height='20%', width='90%'), placeholder='Enter your answer here...')

**What is the complexed energy? Is this a strong complexed energy?**

Textarea(value='', layout=Layout(height='20%', width='90%'), placeholder='Enter your answer here...')

**What is the number of residues on side 1 vs side 2?**

Textarea(value='', layout=Layout(height='20%', width='90%'), placeholder='Enter your answer here...')

**What is your per residue energy?**

Textarea(value='', layout=Layout(height='20%', width='90%'), placeholder='Enter your answer here...')

In [8]:
# @title
import pandas as pd

from pyrosetta.rosetta.protocols.analysis import InterfaceAnalyzerMover
from pyrosetta.rosetta.protocols.simple_filters import ShapeComplementarityFilter
from pyrosetta.rosetta.core.scoring import get_score_function
from pyrosetta.rosetta.core.scoring.sasa import SasaCalc

# -----------------------------
# Total score
# -----------------------------
scorefxn = get_score_function()

total_score = scorefxn(pose)

# -----------------------------
# Interface analysis
# -----------------------------
iam = InterfaceAnalyzerMover(interface)

try:
    iam.set_compute_interface_delta_hbond_unsat(True)
except:
    pass

iam.set_compute_packstat(True)
iam.apply(pose)

# -----------------------------
# Shape Complementarity
# -----------------------------
sc_filter = ShapeComplementarityFilter()

try:
    sc_value = sc_filter.compute(pose)
except:
    sc_value = None

# -----------------------------
# Total SASA
# -----------------------------
sasa_calc = SasaCalc()
sasa_calc.calculate(pose)

total_sasa = sasa_calc.get_total_sasa()

# -----------------------------
# Collect results
# -----------------------------
results = {
    "score": total_score,
    "dG_separated": iam.get_interface_dG(),
    "dSASA_int": iam.get_interface_delta_sasa(),
    "delta_unsatHbonds": iam.get_interface_delta_hbond_unsat(),
    "sc": sc_value,
    "sasa": total_sasa,
}

df_small = pd.DataFrame(
    list(results.items()),
    columns=["Metric", "Value"]
)

display(df_small)
# ---------------------------------
# Save CSV named after PDB
# ---------------------------------

csv_small_name = pdb_file.replace(".pdb", "_rosetta_metrics_small.csv")

df_small.to_csv(csv_name, index=False)

print(f"\nSaved: {csv_small_name}")

core.scoring.ScoreFunctionFactory: SCOREFUNCTION: ref2015
protocols.analysis.InterfaceAnalyzerMover: Using explicit constructor
protocols.analysis.InterfaceAnalyzerMover: Using interface constructor
protocols.analysis.InterfaceAnalyzerMover: [ WARNING ] In InterfaceAnalyzerMover, calculator Sasa_1 already exists, this is hopefully correct for your purposes
protocols.analysis.InterfaceAnalyzerMover: [ WARNING ] In InterfaceAnalyzerMover, calculator InterfaceNeighborDefinition_1 already exists, this is hopefully correct for your purposes
protocols.analysis.InterfaceAnalyzerMover: [ WARNING ] In InterfaceAnalyzerMover, calculator InterfaceDeltaEnergetics_1 already exists, this is hopefully correct for your purposes
protocols.analysis.InterfaceAnalyzerMover: [ WARNING ] In InterfaceAnalyzerMover, calculator NumberHBonds_1 already exists, this is hopefully correct for your purposes
protocols.analysis.InterfaceAnalyzerMover: [ WARNING ] In InterfaceAnalyzerMover, calculator BuriedUnsatisfiedPolars_1 already exists, this is hopefully correct for your purposes
protocols.analysis.InterfaceAnalyzerMover: Making an interface set with fixed chains
protocols.analysis.InterfaceAnalyzerMover: Interface set residues total: 69
protocols.analysis.InterfaceAnalyzerMover: NULL scorefunction. Initialize from cmd line.
core.scoring.ScoreFunctionFactory: SCOREFUNCTION: ref2015
protocols.analysis.InterfaceAnalyzerMover: Detecting disulfides in the separated pose.
protocols.analysis.InterfaceAnalyzerMover: Calculating dSASA
protocols.analysis.InterfaceAnalyzerMover: Calculating per-res dSASA data
protocols.analysis.InterfaceAnalyzerMover: included_nres: 416
protocols.analysis.InterfaceAnalyzerMover: Making hbond ScoreFunction with bb-bb energy method options
core.scoring.ScoreFunctionFactory: SCOREFUNCTION: ref2015
protocols.analysis.InterfaceAnalyzerMover: Found Hbond between chains: 2 and 1
protocols.analysis.InterfaceAnalyzerMover: Found Hbond between chains: 2 and 1
protocols.analysis.InterfaceAnalyzerMover: Found Hbond between chains: 2 and 1
protocols.analysis.InterfaceAnalyzerMover: Found Hbond between chains: 2 and 1
protocols.analysis.InterfaceAnalyzerMover: Found Hbond between chains: 1 and 2
protocols.analysis.InterfaceAnalyzerMover: Found Hbond between chains: 2 and 1
protocols.analysis.InterfaceAnalyzerMover: Computing interface packstats.
protocols.analysis.InterfaceAnalyzerMover: Total: 416 PackScoresTotal: 416
protocols.analysis.InterfaceAnalyzerMover: Computing delta unsat polar residues...
protocols.analysis.InterfaceAnalyzerMover: Computing Shape Complementarity Score...
protocols.analysis.InterfaceAnalyzerMover: Upstream chain(s) numbers: 1,
protocols.analysis.InterfaceAnalyzerMover: Downstream chain(s) numbers: 2,

              Metric                                              Value
0              score                                        -914.572731
1       dG_separated                                         -24.960541
2          dSASA_int                                        1807.967622
3  delta_unsatHbonds                                                  7
4                 sc  <pyrosetta.rosetta.core.scoring.sc._RESULTS ob...
5               sasa                                       20981.078125

Saved: r4_i6_0_85_seq_1049_seq_911_unrelaxed_rank_001_alphafold2_multimer_v3_model_1_seed_000_relaxed_rosetta_metrics_small.csv

In [9]:
# @title
import ipywidgets as widgets
from IPython.display import display, Markdown

display(Markdown("## Checkpoint:Interface Questions continued"))

questions = {
    "Interface Analyzer Questions continued": [
        "What is your score?",
        "What is dSASA_int? What does this say about the SASA when the complex is bound vs when not bound?",
        "What is dG_separated? What does this say about the dG when the complex is bound vs when not bound?",
        "What is your SASA?"
    ],
}
answer_boxes = {}

for section, qs in questions.items():

    display(Markdown(f"### {section}"))

    for q in qs:

        display(Markdown(f"**{q}**"))

        box = widgets.Textarea(
            placeholder="Enter your answer here...",
            layout=widgets.Layout(width='90%', height='20%')
        )

        answer_boxes[q] = box
        display(box)

## Checkpoint:Interface Questions continued

### Interface Analyzer Questions continued

**What is your score?**

Textarea(value='', layout=Layout(height='20%', width='90%'), placeholder='Enter your answer here...')

**What is dSASA_int? What does this say about the SASA when the complex is bound vs when not bound?**

Textarea(value='', layout=Layout(height='20%', width='90%'), placeholder='Enter your answer here...')

**What is dG_separated? What does this say about the dG when the complex is bound vs when not bound?**

Textarea(value='', layout=Layout(height='20%', width='90%'), placeholder='Enter your answer here...')

**What is your SASA?**

Textarea(value='', layout=Layout(height='20%', width='90%'), placeholder='Enter your answer here...')

##Optional: Relaxing (~5 mins)
Relaxing is a Rosetta function that will take your protein structure and try to minimize the energy of your protein by slightly moving side chains to get closer to an energy minima

In [10]:
# @title
import ipywidgets as widgets
from IPython.display import display, Markdown

display(Markdown("## Checkpoint: Relaxing Questions"))

questions = {
    "Relaxing question": [
        "Do you think that relaxing the structure will minimize you Rosetta Ref2015 score? Why?",

    ],
}
answer_boxes = {}

for section, qs in questions.items():

    display(Markdown(f"### {section}"))

    for q in qs:

        display(Markdown(f"**{q}**"))

        box = widgets.Textarea(
            placeholder="Enter your answer here...",
            layout=widgets.Layout(width='90%', height='20%')
        )

        answer_boxes[q] = box
        display(box)

## Checkpoint: Relaxing Questions

### Relaxing question

**Do you think that relaxing the structure will minimize you Rosetta Ref2015 score? Why?**

Textarea(value='', layout=Layout(height='20%', width='90%'), placeholder='Enter your answer here...')

In [11]:
# @title
from pyrosetta import *
from pyrosetta.rosetta.protocols.relax import FastRelax
from pyrosetta.rosetta.core.scoring import get_score_function

# -----------------------------
# Load original structure
# -----------------------------

original_pose = pose_from_pdb(pdb_file)

# Make a copy for relaxation
relaxed_pose = Pose()
relaxed_pose.assign(original_pose)

# -----------------------------
# Score function
# -----------------------------

scorefxn = get_score_function()

# Score before relaxation
score_before = scorefxn(original_pose)

print("Initial score:")
print(score_before)

# -----------------------------
# FastRelax
# -----------------------------

relax = FastRelax()

relax.set_scorefxn(scorefxn)

# Fewer repeats for Colab speed
relax.max_iter(200)

print("\nRunning FastRelax...")

relax.apply(relaxed_pose)

# -----------------------------
# Score after relaxation
# -----------------------------

score_after = scorefxn(relaxed_pose)

print("\nRelax complete")

print(f"\nScore before: {score_before:.3f}")
print(f"Score after : {score_after:.3f}")
print(f"Improvement : {score_before - score_after:.3f}")

# -----------------------------
# Save relaxed PDB
# -----------------------------

relaxed_pdb = pdb_file.replace(".pdb", "_relaxed.pdb")

relaxed_pose.dump_pdb(relaxed_pdb)

print(f"\nSaved: {relaxed_pdb}")

core.import_pose.import_pose: File 'r4_i6_0_85_seq_1049_seq_911_unrelaxed_rank_001_alphafold2_multimer_v3_model_1_seed_000_relaxed.pdb' automatically determined to be of type PDB from contents.
core.scoring.ScoreFunctionFactory: SCOREFUNCTION: ref2015
Initial score:
-914.5727314502806
protocols.relax.RelaxScriptManager: Reading relax scripts list from database.
core.scoring.ScoreFunctionFactory: SCOREFUNCTION: ref2015
protocols.relax.RelaxScriptManager: Looking for MonomerRelax2019.txt
protocols.relax.RelaxScriptManager: ================== Reading script file: /usr/local/lib/python3.12/dist-packages/pyrosetta/database/sampling/relax_scripts/MonomerRelax2019.txt ==================
protocols.relax.RelaxScriptManager: repeat %%nrepeats%%
protocols.relax.RelaxScriptManager: coord_cst_weight 1.0
protocols.relax.RelaxScriptManager: scale:fa_rep 0.040
protocols.relax.RelaxScriptManager: repack
protocols.relax.RelaxScriptManager: scale:fa_rep 0.051
protocols.relax.RelaxScriptManager: min 0.01
protocols.relax.RelaxScriptManager: coord_cst_weight 0.5
protocols.relax.RelaxScriptManager: scale:fa_rep 0.265
protocols.relax.RelaxScriptManager: repack
protocols.relax.RelaxScriptManager: scale:fa_rep 0.280
protocols.relax.RelaxScriptManager: min 0.01
protocols.relax.RelaxScriptManager: coord_cst_weight 0.0
protocols.relax.RelaxScriptManager: scale:fa_rep 0.559
protocols.relax.RelaxScriptManager: repack
protocols.relax.RelaxScriptManager: scale:fa_rep 0.581
protocols.relax.RelaxScriptManager: min 0.01
protocols.relax.RelaxScriptManager: coord_cst_weight 0.0
protocols.relax.RelaxScriptManager: scale:fa_rep 1
protocols.relax.RelaxScriptManager: repack
protocols.relax.RelaxScriptManager: min 0.00001
protocols.relax.RelaxScriptManager: accept_to_best
protocols.relax.RelaxScriptManager: endrepeat

Running FastRelax...
protocols.relax.FastRelax: CMD: repeat  -914.573  0  0  0.55
protocols.relax.FastRelax: CMD: coord_cst_weight  -914.573  0  0  0.55
protocols.relax.FastRelax: CMD: scale:fa_rep  -1287.52  0  0  0.022
core.pack.task: Packer task: initialize from command line()
core.pack.pack_rotamers: built 11027 rotamers at 416 positions.
core.pack.interaction_graph.interaction_graph_factory: Instantiating DensePDInteractionGraph
protocols.relax.FastRelax: CMD: repack  -1488.52  0  0  0.022
protocols.relax.FastRelax: CMD: scale:fa_rep  -1476.17  0  0  0.02805
core.optimization.Minimizer: [ WARNING ] LBFGS MAX CYCLES 200 EXCEEDED, BUT FUNC NOT CONVERGED!
protocols.relax.FastRelax: CMD: min  -1985.2  1.8722  1.8722  0.02805
protocols.relax.FastRelax: CMD: coord_cst_weight  -1985.2  1.8722  1.8722  0.02805
protocols.relax.FastRelax: CMD: scale:fa_rep  -1048.38  1.8722  1.8722  0.14575
core.pack.task: Packer task: initialize from command line()
core.pack.pack_rotamers: built 11298 rotamers at 416 positions.
core.pack.interaction_graph.interaction_graph_factory: Instantiating DensePDInteractionGraph
protocols.relax.FastRelax: CMD: repack  -1137.01  1.8722  1.8722  0.14575
protocols.relax.FastRelax: CMD: scale:fa_rep  -1081.95  1.8722  1.8722  0.154
protocols.relax.FastRelax: CMD: min  -1632.64  1.46114  1.46114  0.154
protocols.relax.FastRelax: CMD: coord_cst_weight  -1632.64  1.46114  1.46114  0.154
protocols.relax.FastRelax: CMD: scale:fa_rep  -1385.55  1.46114  1.46114  0.30745
core.pack.task: Packer task: initialize from command line()
core.pack.pack_rotamers: built 10133 rotamers at 416 positions.
core.pack.interaction_graph.interaction_graph_factory: Instantiating DensePDInteractionGraph
protocols.relax.FastRelax: CMD: repack  -1388.03  1.46114  1.46114  0.30745
protocols.relax.FastRelax: CMD: scale:fa_rep  -1368.75  1.46114  1.46114  0.31955
protocols.relax.FastRelax: CMD: min  -1446.55  1.35303  1.35303  0.31955
protocols.relax.FastRelax: CMD: coord_cst_weight  -1446.55  1.35303  1.35303  0.31955
protocols.relax.FastRelax: CMD: scale:fa_rep  -1232.03  1.35303  1.35303  0.55
core.pack.task: Packer task: initialize from command line()
core.pack.pack_rotamers: built 9695 rotamers at 416 positions.
core.pack.interaction_graph.interaction_graph_factory: Instantiating DensePDInteractionGraph
protocols.relax.FastRelax: CMD: repack  -1232.99  1.35303  1.35303  0.55
protocols.relax.FastRelax: CMD: min  -1288.76  1.26929  1.26929  0.55
protocols.relax.FastRelax: MRP: 0  -1288.76  -1288.76  1.26929  1.26929
protocols.relax.FastRelax: CMD: accept_to_best  -1288.76  1.26929  1.26929  0.55
protocols.relax.FastRelax: CMD: endrepeat  -1288.76  1.26929  1.26929  0.55
protocols.relax.FastRelax: CMD: coord_cst_weight  -1288.76  1.26929  1.26929  0.55
protocols.relax.FastRelax: CMD: scale:fa_rep  -1626.54  1.26929  1.26929  0.022
core.pack.task: Packer task: initialize from command line()
core.pack.pack_rotamers: built 11141 rotamers at 416 positions.
core.pack.interaction_graph.interaction_graph_factory: Instantiating DensePDInteractionGraph
protocols.relax.FastRelax: CMD: repack  -1669.31  1.26929  1.26929  0.022
protocols.relax.FastRelax: CMD: scale:fa_rep  -1658.68  1.26929  1.26929  0.02805
core.optimization.Minimizer: [ WARNING ] LBFGS MAX CYCLES 200 EXCEEDED, BUT FUNC NOT CONVERGED!
protocols.relax.FastRelax: CMD: min  -2048.02  2.03036  2.03036  0.02805
protocols.relax.FastRelax: CMD: coord_cst_weight  -2048.02  2.03036  2.03036  0.02805
protocols.relax.FastRelax: CMD: scale:fa_rep  -1135.89  2.03036  2.03036  0.14575
core.pack.task: Packer task: initialize from command line()
core.pack.pack_rotamers: built 11136 rotamers at 416 positions.
core.pack.interaction_graph.interaction_graph_factory: Instantiating DensePDInteractionGraph
protocols.relax.FastRelax: CMD: repack  -1193.79  2.03036  2.03036  0.14575
protocols.relax.FastRelax: CMD: scale:fa_rep  -1138.22  2.03036  2.03036  0.154
protocols.relax.FastRelax: CMD: min  -1659.31  1.58783  1.58783  0.154
protocols.relax.FastRelax: CMD: coord_cst_weight  -1659.31  1.58783  1.58783  0.154
protocols.relax.FastRelax: CMD: scale:fa_rep  -1409.26  1.58783  1.58783  0.30745
core.pack.task: Packer task: initialize from command line()
core.pack.pack_rotamers: built 10189 rotamers at 416 positions.
core.pack.interaction_graph.interaction_graph_factory: Instantiating DensePDInteractionGraph
protocols.relax.FastRelax: CMD: repack  -1412.16  1.58783  1.58783  0.30745
protocols.relax.FastRelax: CMD: scale:fa_rep  -1392.9  1.58783  1.58783  0.31955
protocols.relax.FastRelax: CMD: min  -1467.52  1.37911  1.37911  0.31955
protocols.relax.FastRelax: CMD: coord_cst_weight  -1467.52  1.37911  1.37911  0.31955
protocols.relax.FastRelax: CMD: scale:fa_rep  -1250.67  1.37911  1.37911  0.55
core.pack.task: Packer task: initialize from command line()
core.pack.pack_rotamers: built 9784 rotamers at 416 positions.
core.pack.interaction_graph.interaction_graph_factory: Instantiating DensePDInteractionGraph
protocols.relax.FastRelax: CMD: repack  -1252.65  1.37911  1.37911  0.55
protocols.relax.FastRelax: CMD: min  -1308.84  1.23455  1.23455  0.55
protocols.relax.FastRelax: MRP: 1  -1308.84  -1308.84  1.23455  1.23455
protocols.relax.FastRelax: CMD: accept_to_best  -1308.84  1.23455  1.23455  0.55
protocols.relax.FastRelax: CMD: endrepeat  -1308.84  1.23455  1.23455  0.55
protocols.relax.FastRelax: CMD: coord_cst_weight  -1308.84  1.23455  1.23455  0.55
protocols.relax.FastRelax: CMD: scale:fa_rep  -1648.52  1.23455  1.23455  0.022
core.pack.task: Packer task: initialize from command line()
core.pack.pack_rotamers: built 11234 rotamers at 416 positions.
core.pack.interaction_graph.interaction_graph_factory: Instantiating DensePDInteractionGraph
protocols.relax.FastRelax: CMD: repack  -1687.66  1.23455  1.23455  0.022
protocols.relax.FastRelax: CMD: scale:fa_rep  -1678.43  1.23455  1.23455  0.02805
core.optimization.Minimizer: [ WARNING ] LBFGS MAX CYCLES 200 EXCEEDED, BUT FUNC NOT CONVERGED!
protocols.relax.FastRelax: CMD: min  -2054.06  1.93986  1.93986  0.02805
protocols.relax.FastRelax: CMD: coord_cst_weight  -2054.06  1.93986  1.93986  0.02805
protocols.relax.FastRelax: CMD: scale:fa_rep  -1157.88  1.93986  1.93986  0.14575
core.pack.task: Packer task: initialize from command line()
core.pack.pack_rotamers: built 11250 rotamers at 416 positions.
core.pack.interaction_graph.interaction_graph_factory: Instantiating DensePDInteractionGraph
protocols.relax.FastRelax: CMD: repack  -1207.97  1.93986  1.93986  0.14575
protocols.relax.FastRelax: CMD: scale:fa_rep  -1152.68  1.93986  1.93986  0.154
protocols.relax.FastRelax: CMD: min  -1670.48  1.3815  1.3815  0.154
protocols.relax.FastRelax: CMD: coord_cst_weight  -1670.48  1.3815  1.3815  0.154
protocols.relax.FastRelax: CMD: scale:fa_rep  -1423.49  1.3815  1.3815  0.30745
core.pack.task: Packer task: initialize from command line()
core.pack.pack_rotamers: built 10221 rotamers at 416 positions.
core.pack.interaction_graph.interaction_graph_factory: Instantiating DensePDInteractionGraph
protocols.relax.FastRelax: CMD: repack  -1424.33  1.3815  1.3815  0.30745
protocols.relax.FastRelax: CMD: scale:fa_rep  -1405.13  1.3815  1.3815  0.31955
protocols.relax.FastRelax: CMD: min  -1475.54  1.21939  1.21939  0.31955
protocols.relax.FastRelax: CMD: coord_cst_weight  -1475.54  1.21939  1.21939  0.31955
protocols.relax.FastRelax: CMD: scale:fa_rep  -1261.03  1.21939  1.21939  0.55
core.pack.task: Packer task: initialize from command line()
core.pack.pack_rotamers: built 9656 rotamers at 416 positions.
core.pack.interaction_graph.interaction_graph_factory: Instantiating DensePDInteractionGraph
protocols.relax.FastRelax: CMD: repack  -1263.15  1.21939  1.21939  0.55
protocols.relax.FastRelax: CMD: min  -1315.73  1.30803  1.30803  0.55
protocols.relax.FastRelax: MRP: 2  -1315.73  -1315.73  1.30803  1.30803
protocols.relax.FastRelax: CMD: accept_to_best  -1315.73  1.30803  1.30803  0.55
protocols.relax.FastRelax: CMD: endrepeat  -1315.73  1.30803  1.30803  0.55
protocols.relax.FastRelax: CMD: coord_cst_weight  -1315.73  1.30803  1.30803  0.55
protocols.relax.FastRelax: CMD: scale:fa_rep  -1654.99  1.30803  1.30803  0.022
core.pack.task: Packer task: initialize from command line()
core.pack.pack_rotamers: built 11023 rotamers at 416 positions.
core.pack.interaction_graph.interaction_graph_factory: Instantiating DensePDInteractionGraph
protocols.relax.FastRelax: CMD: repack  -1690.54  1.30803  1.30803  0.022
protocols.relax.FastRelax: CMD: scale:fa_rep  -1680.56  1.30803  1.30803  0.02805
protocols.relax.FastRelax: CMD: min  -2057.16  2.04342  2.04342  0.02805
protocols.relax.FastRelax: CMD: coord_cst_weight  -2057.16  2.04342  2.04342  0.02805
protocols.relax.FastRelax: CMD: scale:fa_rep  -1135.95  2.04342  2.04342  0.14575
core.pack.task: Packer task: initialize from command line()
core.pack.pack_rotamers: built 10843 rotamers at 416 positions.
core.pack.interaction_graph.interaction_graph_factory: Instantiating DensePDInteractionGraph
protocols.relax.FastRelax: CMD: repack  -1206.87  2.04342  2.04342  0.14575
protocols.relax.FastRelax: CMD: scale:fa_rep  -1152.67  2.04342  2.04342  0.154
protocols.relax.FastRelax: CMD: min  -1663.01  1.56631  1.56631  0.154
protocols.relax.FastRelax: CMD: coord_cst_weight  -1663.01  1.56631  1.56631  0.154
protocols.relax.FastRelax: CMD: scale:fa_rep  -1413.7  1.56631  1.56631  0.30745
core.pack.task: Packer task: initialize from command line()
core.pack.pack_rotamers: built 10098 rotamers at 416 positions.
core.pack.interaction_graph.interaction_graph_factory: Instantiating DensePDInteractionGraph
protocols.relax.FastRelax: CMD: repack  -1415.18  1.56631  1.56631  0.30745
protocols.relax.FastRelax: CMD: scale:fa_rep  -1395.79  1.56631  1.56631  0.31955
protocols.relax.FastRelax: CMD: min  -1459.91  1.41229  1.41229  0.31955
protocols.relax.FastRelax: CMD: coord_cst_weight  -1459.91  1.41229  1.41229  0.31955
protocols.relax.FastRelax: CMD: scale:fa_rep  -1231.42  1.41229  1.41229  0.55
core.pack.task: Packer task: initialize from command line()
core.pack.pack_rotamers: built 9736 rotamers at 416 positions.
core.pack.interaction_graph.interaction_graph_factory: Instantiating DensePDInteractionGraph
protocols.relax.FastRelax: CMD: repack  -1232.21  1.41229  1.41229  0.55
protocols.relax.FastRelax: CMD: min  -1304.58  1.30718  1.30718  0.55
protocols.relax.FastRelax: MRP: 3  -1304.58  -1315.73  1.30803  1.30803
protocols.relax.FastRelax: CMD: accept_to_best  -1304.58  1.30718  1.30718  0.55
protocols.relax.FastRelax: CMD: endrepeat  -1304.58  1.30718  1.30718  0.55
protocols.relax.FastRelax: CMD: coord_cst_weight  -1304.58  1.30718  1.30718  0.55
protocols.relax.FastRelax: CMD: scale:fa_rep  -1645.17  1.30718  1.30718  0.022
core.pack.task: Packer task: initialize from command line()
core.pack.pack_rotamers: built 11350 rotamers at 416 positions.
core.pack.interaction_graph.interaction_graph_factory: Instantiating DensePDInteractionGraph
protocols.relax.FastRelax: CMD: repack  -1696.33  1.30718  1.30718  0.022
protocols.relax.FastRelax: CMD: scale:fa_rep  -1686.97  1.30718  1.30718  0.02805
core.optimization.Minimizer: [ WARNING ] LBFGS MAX CYCLES 200 EXCEEDED, BUT FUNC NOT CONVERGED!
protocols.relax.FastRelax: CMD: min  -2065.66  2.16131  2.16131  0.02805
protocols.relax.FastRelax: CMD: coord_cst_weight  -2065.66  2.16131  2.16131  0.02805
protocols.relax.FastRelax: CMD: scale:fa_rep  -1134.58  2.16131  2.16131  0.14575
core.pack.task: Packer task: initialize from command line()
core.pack.pack_rotamers: built 10946 rotamers at 416 positions.
core.pack.interaction_graph.interaction_graph_factory: Instantiating DensePDInteractionGraph
protocols.relax.FastRelax: CMD: repack  -1194.47  2.16131  2.16131  0.14575
protocols.relax.FastRelax: CMD: scale:fa_rep  -1137.43  2.16131  2.16131  0.154
core.optimization.Minimizer: [ WARNING ] LBFGS MAX CYCLES 200 EXCEEDED, BUT FUNC NOT CONVERGED!
protocols.relax.FastRelax: CMD: min  -1676.69  1.6405  1.6405  0.154
protocols.relax.FastRelax: CMD: coord_cst_weight  -1676.69  1.6405  1.6405  0.154
protocols.relax.FastRelax: CMD: scale:fa_rep  -1427.71  1.6405  1.6405  0.30745
core.pack.task: Packer task: initialize from command line()
core.pack.pack_rotamers: built 10115 rotamers at 416 positions.
core.pack.interaction_graph.interaction_graph_factory: Instantiating DensePDInteractionGraph
protocols.relax.FastRelax: CMD: repack  -1429.12  1.6405  1.6405  0.30745
protocols.relax.FastRelax: CMD: scale:fa_rep  -1409.62  1.6405  1.6405  0.31955
protocols.relax.FastRelax: CMD: min  -1478.27  1.44899  1.44899  0.31955
protocols.relax.FastRelax: CMD: coord_cst_weight  -1478.27  1.44899  1.44899  0.31955
protocols.relax.FastRelax: CMD: scale:fa_rep  -1256.48  1.44899  1.44899  0.55
core.pack.task: Packer task: initialize from command line()
core.pack.pack_rotamers: built 9659 rotamers at 416 positions.
core.pack.interaction_graph.interaction_graph_factory: Instantiating DensePDInteractionGraph
protocols.relax.FastRelax: CMD: repack  -1258.76  1.44899  1.44899  0.55
protocols.relax.FastRelax: CMD: min  -1314.42  1.40583  1.40583  0.55
protocols.relax.FastRelax: MRP: 4  -1314.42  -1315.73  1.30803  1.30803
protocols.relax.FastRelax: CMD: accept_to_best  -1314.42  1.40583  1.40583  0.55
protocols.relax.FastRelax: CMD: endrepeat  -1314.42  1.40583  1.40583  0.55
protocols::checkpoint: Deleting checkpoints of FastRelax

Relax complete

Score before: -914.573
Score after : -1315.734
Improvement : 401.162

Saved: r4_i6_0_85_seq_1049_seq_911_unrelaxed_rank_001_alphafold2_multimer_v3_model_1_seed_000_relaxed_relaxed.pdb

In [12]:
# @title
import ipywidgets as widgets
from IPython.display import display, Markdown

display(Markdown("## Checkpoint: Relaxing Questions"))

questions = {
    "Relaxing question": [
        "Did relaxing the structure minimize the score?",
        "How much did the score get minimized if at all?",

    ],
}
answer_boxes = {}

for section, qs in questions.items():

    display(Markdown(f"### {section}"))

    for q in qs:

        display(Markdown(f"**{q}**"))

        box = widgets.Textarea(
            placeholder="Enter your answer here...",
            layout=widgets.Layout(width='90%', height='20%')
        )

        answer_boxes[q] = box
        display(box)

## Checkpoint: Relaxing Questions

### Relaxing question

**Did relaxing the structure minimize the score?**

Textarea(value='', layout=Layout(height='20%', width='90%'), placeholder='Enter your answer here...')

**How much did the score get minimized if at all?**

Textarea(value='', layout=Layout(height='20%', width='90%'), placeholder='Enter your answer here...')